### ISSUE TITLE
[Feat]Push notification for deadline

### ISSUE THREAD

**Issue by Sanat-Jha** [IMGIITRoorkee/Taskly#83] opened 2024-12-22 06:05 UTC
**Is your feature request related to a problem? Please describe.**
How do I get to know if any deadline is near or breached if I don't check the task list manually?

**Describe the solution you'd like**
Give out a push notification one day before any task deadline for a reminder and on the deadline date to inform that it is crossed.

**Comment by Sanat-Jha** [comment] 2024-12-22 06:06
@Akshit517 Please assign toughness tag.

**Comment by sommye-ctr** [comment] 2024-12-22 07:14
Possible duplicate of #68 this?

**Comment by Akshit517** [comment] 2024-12-22 07:35
This issue was addressed in #68. Closing this one.

**Closed** 2024-12-22 07:36 UTC
